# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
array = np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
arr1 = np.ones((3,1))
arr2 = np.zeros((2,1))
np.vstack((arr1,arr2))

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [14]:
arr1 = np.ones((2,3))
arr2 = np.zeros((2,5))
np.hstack((arr1,arr2))

array([[1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [19]:
arr = np.ones((2,5,3))
arr.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [20]:
arr = np.ones((2,5,3))
arr.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [22]:
arr = np.ones(30).reshape(2,3,5)
arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [34]:
arr = np.arange(25).reshape(5,5)
arr*arr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [35]:
arr = np.arange(30).reshape(5,6)
arr.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [39]:
arr.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [38]:
np.median(arr)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [40]:
arr.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [48]:
arr = np.arange(16).reshape(4,4)
arr.diagonal().sum()

30

## Question:13

### Find the determinant of the previous array in Q12?

In [49]:
np.linalg.det(arr)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [52]:
print(np.percentile(arr,5))
np.percentile(arr,95)

0.75


14.25

## Question:15

### How to find if a given array has any null values?

In [53]:
np.isnan(arr)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])